@echo off
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_235.pcd" "235.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_245.pcd" "245.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_255.pcd" "255.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_265.pcd" "265.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_275.pcd" "275.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_285.pcd" "285.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_295.pcd" "295.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_305.pcd" "305.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_315.pcd" "315.json"
start C:/Users/jbae0/AppData/Local/Microsoft/WindowsApps/python3.9.exe C:/Users/jbae0/OneDrive/Desktop/OXHACK/lidar-visualization/process_data.py "lidar_data/lidar_points_325.pcd" "325.json"